# Generated by Django 5.0 on 2025-12-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, null=True, verbose_name='Название изображения')),
                ('comment', models.CharField(max_length=256, null=True, verbose_name='Комментарий к изображению')),
                ('picture', models.ImageField(blank=True, upload_to='galery/', verbose_name='Изображение')),
                ('update', models.DateTimeField(auto_now_add=True, verbose_name='Время загрузки')),
            ],
        ),
    ]
