# Generated by Django 5.0 on 2025-12-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='comment',
            field=models.CharField(blank=True, max_length=256, verbose_name='Комментарий к изображению'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Название изображения'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='galery/', verbose_name='Изображение'),
        ),
    ]
