# Generated by Django 5.0 on 2025-12-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0002_alter_picture_comment_alter_picture_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='Название документу')),
                ('comment', models.CharField(blank=True, max_length=256, verbose_name='Комментарий к документу')),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Документ')),
                ('update', models.DateTimeField(auto_now_add=True, verbose_name='Время загрузки')),
            ],
        ),
    ]
