# Generated by Django 5.0 on 2025-12-24 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0003_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='Название документу')),
                ('comment', models.CharField(blank=True, max_length=256, verbose_name='Комментарий к документу')),
            ],
        ),
        migrations.CreateModel(
            name='CompLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='elements.component')),
                ('parentC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='elements.component')),
            ],
        ),
        migrations.CreateModel(
            name='CompDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dokument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elements.document')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elements.component')),
            ],
        ),
        migrations.CreateModel(
            name='CompPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elements.component')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elements.picture')),
            ],
        ),
    ]
