# Generated by Django 5.0 on 2025-12-24 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0004_component_complink_compdoc_comppic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complink',
            name='childC',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childC', to='elements.component'),
        ),
        migrations.AlterField(
            model_name='complink',
            name='parentC',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parentC', to='elements.component'),
        ),
    ]
