# Generated by Django 5.0 on 2025-12-24 10:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0005_alter_complink_childc_alter_complink_parentc'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='contract',
            field=models.BooleanField(default=False, verbose_name='Является заказом'),
        ),
        migrations.AddField(
            model_name='component',
            name='docs',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Документ'),
        ),
        migrations.AddField(
            model_name='component',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='galery/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='component',
            name='update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время загрузки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='component',
            name='comment',
            field=models.CharField(blank=True, max_length=256, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Название'),
        ),
    ]
