# Generated by Django 5.0 on 2025-12-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0006_component_contract_component_docs_component_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='docs',
        ),
        migrations.RemoveField(
            model_name='component',
            name='images',
        ),
        migrations.AddField(
            model_name='component',
            name='docs',
            field=models.ManyToManyField(through='elements.CompDoc', to='elements.document'),
        ),
        migrations.AddField(
            model_name='component',
            name='images',
            field=models.ManyToManyField(through='elements.CompPic', to='elements.picture'),
        ),
    ]
