# Generated by Django 5.0 on 2025-12-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0007_remove_component_docs_remove_component_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
